name: flutter_application_1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  audioplayer: ^0.8.1
  awesome_notifications: ^0.7.4+1
  card_swiper: ^2.0.4
  flutter:
    sdk: flutter
  flutter_background: ^1.2.0
  flutter_local_notifications: ^14.1.1
  just_audio: ^0.9.34
  on_audio_query: ^2.9.0
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - android/app/src/main/res/drawable/next.png
    - android/app/src/main/res/drawable/pre.png
    - android/app/src/main/res/drawable/play.png
    - android/app/src/main/res/drawable/pause.png

